package fr.improve.struts.taglib.layout;

import javax.servlet.jsp.JspException;

import fr.improve.struts.taglib.layout.event.StaticCodeIncludeLayoutEvent;
import fr.improve.struts.taglib.layout.event.StaticCodeIncludeListener;
import fr.improve.struts.taglib.layout.util.TagUtils;

/**
 * Tag creating a DIV HTML element.
 * 
 * This tagimplements the StaticCodeIncludeListener so that DIV generated by Struts-Layout
 * are positioned out of this DIV.
 * 
 * This helps positioning of popup (like the calendar)
 * 
 * @author JN RIBETTE
 */
public class DivTag extends LayoutTagSupport implements StaticCodeIncludeListener {
	/**
	 * Static HTML code to write.
	 */
	protected StringBuffer staticCode = new StringBuffer();
	
	/**
	 * Attribute styleId
	 */
	private String styleId;
	
	/**
	 * Tag start
	 */
	public int doStartLayoutTag() throws JspException {
		// Start DIV.
		TagUtils.write(pageContext, "<div");
		
		// Add id attribute
		if (styleId!=null) {
			TagUtils.write(pageContext, " id=\"");
			TagUtils.write(pageContext, styleId);
			TagUtils.write(pageContext, "\"");
		}
		// end DIV.
		TagUtils.write(pageContext, ">");
		
		// Evaluate tag content.
		return EVAL_BODY_INCLUDE;
	}
	
	/**
	 * Tag end.
	 */
	public int doEndLayoutTag() throws JspException {
		// End DIV.
		TagUtils.write(pageContext, "</div>");
		
		// Write static HTML code.
		if (staticCode.length()!=0) {
			TagUtils.write(pageContext, staticCode.toString());
		}
		
		// Evaluate page.
		return EVAL_PAGE;
	}
	
	/**
	 * Reset this tags.
	 */
	protected void reset() {
		super.reset();
		staticCode = new StringBuffer();
		styleId = null;
	}

	/**
	 * Handle StaticCodeIncludeLayoutEvent.
	 */
	public Object processStaticCodeIncludeEvent(StaticCodeIncludeLayoutEvent in_event) throws JspException {
		// Envoie le code statique au un listener parent s'il y en a un.
		String lc_value = (String) in_event.sendToParent(this);
		
		// Garde le code statique a générer, s'il n'a pas
		// été traité par le parent.
		staticCode.append(lc_value);
		return "";		
	}

	public String getStyleId() {
		return styleId;
	}

	public void setStyleId(String styleId) {
		this.styleId = styleId;
	}
}
